#!/usr/bin/env python3
MONSTER2 = {
    "0x06": ("Al Rappy", "Pal Rappy"),  # “Al Rappy”, “Pal Rappy”
    "0x58": ("Astark", ""),             # “Astark”, nullptr
    "0x62": ("Ba Boota", ""),           # “Ba Boota”, nullptr
    "0x49": ("Barba Ray", ""),          # “Barba Ray”, nullptr
    "0x49": ("Barba Ray (joint)", ""),  # “Barba Ray (joint)”, nullptr
    "0x08": ("Barbarous Wolf", "Gulgus-gue"),
    "NONE": ("Bee L", "Gee L"),
    "NONE": ("Bee R", "Gee R"),
    "0x09": ("Booma", "Bartle"),
    "0x60": ("Boota", ""),
    "0x28": ("Bulclaw", ""),
    "0x27": ("Bulk", ""),
    "0x1C": ("Canadine", "Canabin"),
    "0x1C": ("Canadine (group)", "Canabin (group)"),
    "0x1D": ("Canane", "Canune"),
    "0x24": ("Chaos Bringer", "Dark Bringer"),
    "0x1F": ("Chaos Sorceror", "Gran Sorceror"),
    "0x26": ("Claw", ""),
    "0x25": ("Dark Belra", "Indi Belra"),
    "NONE": ("Dark Falz (phase 1)", ""),
    "0x2F": ("Dark Falz (phase 2)", ""),
    "0x2F": ("Dark Falz (phase 3)", ""),
    "0x22": ("Dark Gunner", ""),
    "NONE": ("Dark Gunner (control)", ""),
    "NONE": ("Darvant", ""),
    "0x2D": ("De Rol Le", "Dal Ral Lie"),
    "NONE": ("De Rol Le (body)", "Dal Ral Lie (body)"),
    "NONE": ("De Rol Le (mine)", "Dal Ral Lie (mine)"),
    "0x23": ("Death Gunner", ""),
    "0x53": ("Del Lily", ""),
    "0x69": ("Del Rappy (crater)", ""),
    "0x69": ("Del Rappy (desert)", ""),
    "0x48": ("Delbiter", ""),
    "0x47": ("Deldepth", ""),
    "0x1E": ("Delsaber", ""),
    "0x29": ("Dimenian", "Arlan"),
    "0x41": ("Dolmdarl", ""),
    "0x40": ("Dolmolm", ""),
    "0x63": ("Dorphon", ""),
    "0x64": ("Dorphon Eclair", ""),
    "0x2C": ("Dragon", "Sil Dragon"),
    "0x18": ("Dubchic", "Dubchich"),
    "NONE": ("Dubwitch", "Duvuik"),
    "0x51": ("Egg Rappy", ""),
    "NONE": ("Episgard", ""),
    "0x54": ("Epsilon", ""),
    "0x10": ("Evil Shark", "Vulmer"),
    "NONE": ("Gael/Giel", ""),
    "0x4D": ("Gal Gryphon", ""),
    "0x19": ("Garanz", "Baranz"),
    "0x36": ("Gee", ""),
    "0x37": ("Gi Gue", ""),
    "0x3D": ("Gibbles", ""),
    "0x0B": ("Gigobooma", "Tollaw"),
    "0x32": ("Gillchic", "Gillchich"),
    "0x5D": ("Girtablulu", ""),
    "0x0A": ("Gobooma", "Barble"),
    "0x4C": ("Gol Dragon", ""),
    "0x65": ("Goran", ""),
    "0x66": ("Goran Detonator", ""),
    "0x0C": ("Grass Assassin", "Crimson Assassin"),
    "0x12": ("Guil Shark", "Melqueek"),
    "0x50": ("Hallo Rappy", ""),
    "0x17": ("Hidoom", ""),
    "0x01": ("Hildebear", "Hildelt"),
    "0x02": ("Hildeblue", "Hildetorr"),
    "0x52": ("Ill Gill", ""),
    "0x6C": ("Kondrieu", ""),
    "0x6C": ("Kondrieu (spinner)", ""),
    "0x2A": ("La Dimenian", "Merlan"),
    "0x33": ("Love Rappy", ""),
    "0x38": ("Mericarand", ""),
    "0x38": ("Mericarol", ""),
    "0x3A": ("Mericus", ""),
    "0x39": ("Merikle", ""),
    "0x34": ("Merillia", ""),
    "0x35": ("Meriltas", ""),
    "0x5B": ("Merissa A", ""),
    "0x5C": ("Merissa AA", ""),
    "0x16": ("Migium", ""),
    "0x04": ("Monest", "Mothvist"),
    "0x42": ("Morfos", ""),
    "0x03": ("Mothmant", "Mothvert"),
    "0x0F": ("Nano Dragon", ""),
    "0x0E": ("Nar Lily", "Mil Lily"),
    "NONE": ("Olga Flow (phase 1)", ""),
    "0x4E": ("Olga Flow (phase 2)", ""),
    "0x11": ("Pal Shark", "Govulmer"),
    "0x15": ("Pan Arms", ""),
    "0x5F": ("Pazuzu (crater)", ""),
    "0x5F": ("Pazuzu (desert)", ""),
    "0x4A": ("Pig Ray", ""),
    "0x13": ("Pofuilly Slime", ""),
    "0x14": ("Pouilly Slime", ""),
    "0x0D": ("Poison Lily", "Ob Lily"),
    "0x67": ("Pyro Goran", ""),
    "0x05": ("Rag Rappy", "El Rappy"),
    "0x43": ("Recobox", ""),
    "0x44": ("Recon", ""),
    "0x6A": ("Saint-Milion", ""),
    "0x6A": ("Saint-Milion (spinner)", ""),
    "0x4F": ("Saint Rappy", ""),
    "0x68": ("Sand Rappy (crater)", ""),
    "0x68": ("Sand Rappy (desert)", ""),
    "0x5A": ("Satellite Lizard (crater)", ""),
    "0x5A": ("Satellite Lizard (desert)", ""),
    "0x07": ("Savage Wolf", "Gulgus"),
    "0x6B": ("Shambertin", ""),
    "0x6B": ("Shambertin (spinner)", ""),
    "0x1A": ("Sinow Beat", "Sinow Blue"),
    "0x3E": ("Sinow Berill", ""),
    "0x1B": ("Sinow Gold", "Sinow Red"),
    "0x3F": ("Sinow Spigell", ""),
    "0x46": ("Sinow Zele", ""),
    "0x45": ("Sinow Zoa", ""),
    "0x2B": ("So Dimenian", "Del-D"),
    "0x3B": ("Ul Gibbon", ""),
    "0x4B": ("Ul Ray", ""),
    "NONE": ("Vol Opt (phase 1)", "Vol Opt ver.2 (phase 1)"),
    "0x2E": ("Vol Opt (phase 2)", "Vol Opt ver.2 (phase 2)"),
    "NONE": ("Vol Opt (amp)", "Vol Opt ver.2 (amp)"),
    "NONE": ("Vol Opt (core)", "Vol Opt ver.2 (core)"),
    "NONE": ("Vol Opt (monitor)", "Vol Opt ver.2 (monitor)"),
    "NONE": ("Vol Opt (pillar)", "Vol Opt ver.2 (pillar)"),
    "0x59": ("Yowie (crater)", ""),
    "0x59": ("Yowie (desert)", ""),
    "0x61": ("Ze Boota", ""),
    "0x3C": ("Zol Gibbon", ""),
    "0x5E": ("Zu (crater)", ""),
    "0x5E": ("Zu (desert)", ""),
}
AREA2 = {
    "00": "Pioneer 2 (no drops)",
    "01": "Forest 1",
    "02": "Forest 2",
    "03": "Cave 1",
    "04": "Cave 2",
    "05": "Cave 3",
    "06": "Mine 1",
    "07": "Mine 2",
    "08": "Ruins 1",
    "09": "Ruins 2",
    "0A": "Ruins 3",
    "0B": "Dragon -> Cave 1",
    "0C": "De Rol Le -> Mine 1",
    "0D": "Vol Opt -> Ruins 1",
    "0E": "Dark Falz -> Ruins 3",
    "0F": "Lobby (no drops)",
    "10": "Palace -> Ruins 3",
    "11": "Spaceship -> Ruins 3",

    # Episode 2
    "12": "Lab (no drops)",
    "13": "VR Temple Alpha",
    "14": "VR Temple Beta",
    "15": "VR Spaceship Alpha",
    "16": "VR Spaceship Beta",
    "17": "Central Control Area -> Seaside",
    "18": "Jungle North",
    "19": "Jungle South",
    "1A": "Mountain",
    "1B": "Seaside",
    "1C": "Seabed Upper",
    "1D": "Seabed Lower",
    "1E": "Gal Gryphon -> Seabed Upper",
    "1F": "Olga Flow -> Seabed Lower",
    "20": "Barba Ray -> VR Spaceship Alpha",
    "21": "Gol Dragon -> Jungle North",
    "22": "Seaside Night -> Seaside",
    "23": "Tower -> Seabed Lower",

    # Episode 4
    "24": "Crater East",
    "25": "Crater West",
    "26": "Crater South",
    "27": "Crater North",
    "28": "Crater Interior",
    "29": "Subterranean Desert 1",
    "2A": "Subterranean Desert 2",
    "2B": "Subterranean Desert 3",
    "2C": "Saint-Milion",
    "2D": "Pioneer 2 (no drops)",
    "2E": "Test area (no drops)",
}